
application:
  fileName: application-uat.yml
  env: ${spring.profiles.active}
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://edutestportal.svc.azuremicroservices.io/eureka/eureka
    instance:
      hostname: localhost